name: machine-learning-hats-2022
channels:
    - pytorch
    - conda-forge
dependencies:
    - numpy
    - uproot
    - h5py
    - tensorflow
    - scikit-learn
    - scikit-optimize
    - matplotlib
    - pandas
    - pytorch
    - torchvision
    - torchaudio
    - cpuonly
    - ipykernel
    - tqdm
    - jupyter
    - networkx
